import type { Metadata } from "next";
import { cookies } from "next/headers"
import { SidebarProvider } from "@/components/ui/sidebar";
import AppSidebar from "@/components/app-sidebar";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const cookieStore = await cookies()
  const defaultOpen = cookieStore.get("sidebar_state")?.value === "true"

  return (
    <html lang="en">
      <body>
        <SidebarProvider defaultOpen={defaultOpen}>
          <div className="hidden md:block">
            <AppSidebar />
          </div>
          <main className="flex-1 flex flex-col">
            <div className="flex-1 flex justify-center">
              {children}
            </div>
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
