import type { Metadata } from "next";
import { cookies } from "next/headers"
import { SidebarProvider } from "@/components/ui/sidebar";
import AppSidebar from "@/components/app-sidebar";
import BottomNav from "@/components/bottom-nav";
import { CircleUser } from "lucide-react";
import { Button } from "@/components/ui/button";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const cookieStore = await cookies()
  const defaultOpen = cookieStore.get("sidebar_state")?.value === "true"

  return (
    <SidebarProvider defaultOpen={defaultOpen}>
      <div className="hidden md:block">
        <AppSidebar />
      </div>
      <main className="flex-1 flex flex-col h-screen overflow-hidden">
        <div className="flex items-center justify-between md:hidden py-4 px-6 flex-shrink-0">
          <header className="text-xl">momento</header>
          <Button variant="ghost" size={"icon"}>
            <CircleUser />
          </Button>
        </div>
        <div className="flex-1 flex justify-center min-h-0">
          {children}
        </div>
        <div className="md:hidden">
          <BottomNav />
        </div>
      </main>
    </SidebarProvider>
  );
}
